name: Clash of Clans - Royal House
favicon: null
layout_spectrum: 0.27246
typography_spectrum: 0.66237
title: Official Website for the Royal House Clan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7552c8'
    - '#461859'
    - '#ff0008'
    - '#a98a76'
    - '#fef1e6'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
