title: Royal House - Official Clan Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4838883
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#FFFFFF'
    - '#70706A'
    - '#0C0D0F'
    - '#433B34'
    - '#C7C7C7'
  rhythmicContrast: 0.4312567
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Clash of Clans - Royal House
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85409
layout_spectrum: 0.4838883
