name: Clash of Clans - Royal House
favicon: null
layout_spectrum: 0.27246
typography_spectrum: 0.07438
title: Royal House - Official Clan Website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#97aab9'
    - '#07306e'
    - '#5a6d8c'
    - '#fefaf7'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
