title: Royal House - Official Clan Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4838883
  brandStrength: 0.625
  lightness: 0.5
  brandColors:
    - '#F5F4EF'
    - '#4FA3FC'
    - '#0C6273'
    - '#C1C0C9'
    - '#000000'
  rhythmicContrast: 0.4312567
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Clash of Clans - Royal House
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85409
layout_spectrum: 0.4838883
