name: Clash of Clans - Royal House
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66237
title: Official Website for the Royal House Clan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03151f'
    - '#d5b463'
    - '#fce002'
    - '#826206'
    - '#f7f3c8'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
