title: Royal House - Official Clan Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4838883
  brandStrength: 0.625
  rhythmicContrast: 0.4312567
  brandColors:
    - '#91BDD4'
    - '#9EF7F8'
    - '#4478A0'
    - '#27427B'
    - '#FFFFFF'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Clash of Clans - Royal House
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85409
layout_spectrum: 0.4838883
