name: Clash of Clans - Royal House
favicon: null
layout_spectrum: 0.72047
typography_spectrum: 0.85409
title: Royal House - Official Clan Website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29251c'
    - '#ffffe6'
    - '#baa518'
    - '#0d956f'
    - '#d46e55'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
