title: Royal House - Official Clan Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.953276
  brandStrength: 0.2228786
  lightness: 0.8200859
  brandColors:
    - '#F1F2F4'
    - '#515562'
    - '#AAD5C6'
    - '#9EA3A6'
    - '#181722'
  rhythmicContrast: 0.1165414
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Clash of Clans - Royal House
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85409
layout_spectrum: 0.4838883
