name: RoyalHouse
favicon: null
layout_spectrum: 0.24121
typography_spectrum: 0.66237
title: Official Website for the Royal House Clan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#e30001'
    - '#7d8295'
    - '#ec4b70'
  brandStrength: 0.0625
  lightness: 0.14734942046925426
  saturation: 0.794752512127161
  rhythmicContrast: 0.18055659160017967
purpose: []
